import React, { useState, useRef, useEffect } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { CharacterProfile, Gender, ArtStyle, Ethnicity, HairStyle, BodyType, BreastSize, ButtSize } from '../types';
import { GENDER_OPTIONS, ART_STYLE_OPTIONS, ETHNICITY_OPTIONS, SKIN_TONES, EYE_COLORS, HAIR_COLORS, HAIR_STYLE_OPTIONS, BODY_TYPE_OPTIONS, BREAST_SIZE_OPTIONS, BUTT_SIZE_OPTIONS, PERSONALITY_OPTIONS, OCCUPATION_OPTIONS, RELATIONSHIP_OPTIONS, HOBBY_OPTIONS } from '../constants';
import ProgressBar from './Header';
import { generateAndDetailCharacterImage, generateCharacterDetails } from '../services/geminiService';
import LoadingSpinner from './LoadingSpinner';

interface CharacterFormProps {
  onSave: (character: CharacterProfile) => void;
  existingCharacter?: CharacterProfile | null;
  onBackToMenu: () => void;
}

const DEFAULT_CHARACTER: CharacterProfile = {
  id: '',
  name: '',
  age: 24,
  gender: Gender.Female,
  style: ArtStyle.Realistic,
  ethnicity: Ethnicity.Asian,
  skinTone: SKIN_TONES[0],
  eyeColor: EYE_COLORS[0],
  hairColor: HAIR_COLORS[0],
  hairStyle: HairStyle.Long,
  bodyType: BodyType.Slim,
  breastSize: BreastSize.Medium,
  buttSize: ButtSize.Medium,
  personality: 'Vui vẻ & hoạt bát',
  occupation: 'Người mẫu',
  relationship: 'Độc thân',
  hobby: 'Du lịch',
  singleImages: [],
  lookbooks: [],
};

const CharacterForm: React.FC<CharacterFormProps> = ({ onSave, existingCharacter, onBackToMenu }) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [character, setCharacter] = useState<CharacterProfile>(
    existingCharacter || { ...DEFAULT_CHARACTER, id: uuidv4() }
  );
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isGeneratingDetails, setIsGeneratingDetails] = useState(false);
  
  // Reference Image State
  const [referenceImageFile, setReferenceImageFile] = useState<File | null>(null);
  const [referencePreview, setReferencePreview] = useState<string | null>(existingCharacter?.referenceImage || null);

  // Clone Image State
  const [cloneImageFile, setCloneImageFile] = useState<File | null>(null);
  const [clonePreview, setClonePreview] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const cloneInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (existingCharacter) {
      setCharacter(existingCharacter);
      if (existingCharacter.referenceImage) {
        setReferencePreview(existingCharacter.referenceImage);
      }
    }
  }, [existingCharacter]);

  const updateField = (field: keyof CharacterProfile, value: any) => {
    setCharacter(prev => ({ ...prev, [field]: value }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>, isClone: boolean = false) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        if (isClone) {
          setCloneImageFile(file);
          setClonePreview(base64);
        } else {
          setReferenceImageFile(file);
          setReferencePreview(base64);
          updateField('referenceImage', base64);
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAIAnalyze = async (source: 'clone' | 'reference') => {
    const imageToAnalyze = source === 'clone' ? clonePreview : referencePreview;
    
    if (!imageToAnalyze) return;

    setIsAnalyzing(true);
    try {
      // Safely extract base64 and mimeType
      const base64Data = imageToAnalyze.split(',')[1];
      const mimeType = imageToAnalyze.substring(imageToAnalyze.indexOf(':') + 1, imageToAnalyze.indexOf(';')) || 'image/jpeg';

      const analysis = await generateAndDetailCharacterImage(base64Data, mimeType);
      
      setCharacter(prev => ({
        ...prev,
        ...analysis,
        // If cloning, we ensure the reference image is set to the clone image for consistency
        // If analyzing reference, we keep the current reference image
        referenceImage: source === 'clone' ? clonePreview! : (prev.referenceImage || referencePreview!),
        // Ensure Visual DNA is set
        publicDescription: analysis.publicDescription
      }));
      
      // --- QUAN TRỌNG: Tự động chuyển đến bước cuối cùng ---
      setCurrentStep(6);
      
      if (source === 'clone') {
          alert("Đã sao chép 'Visual DNA' thành công! Toàn bộ hồ sơ nhân vật đã được tự động điền.");
      } else {
          alert("Đã phân tích ảnh tham khảo thành công! Toàn bộ hồ sơ nhân vật đã được tự động điền.");
      }
    } catch (error) {
      console.error("Analysis failed:", error);
      alert("Không thể phân tích ảnh. Vui lòng thử lại.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleAutoGenerateDetails = async () => {
      setIsGeneratingDetails(true);
      try {
          const details = await generateCharacterDetails(character);
          setCharacter(prev => ({ ...prev, ...details }));
      } catch (e) {
          console.error("Detail generation failed", e);
      } finally {
          setIsGeneratingDetails(false);
      }
  };

  const renderStep1 = () => (
    <div className="space-y-8 animate-fade-in">
        {/* Gender Selection - Compact & Minimal */}
        <div className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
             <label className="block text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Giới tính</label>
             <div className="flex gap-4">
                {GENDER_OPTIONS.map((option) => (
                    <button
                    key={option.value}
                    onClick={() => updateField('gender', option.value)}
                    className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-lg border-2 transition-all duration-200 ${
                        character.gender === option.value
                        ? 'border-pink-500 bg-pink-500/20 text-white shadow-[0_0_15px_rgba(236,72,153,0.3)]'
                        : 'border-gray-700 bg-gray-800 text-gray-400 hover:border-gray-500 hover:bg-gray-750'
                    }`}
                    >
                    {option.value === Gender.Male ? (
                        <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 3h5v5"/><path d="M21 3l-7.1 7.1"/><path d="M5.5 20.5a8.5 8.5 0 1 0 11.5-7.8"/></svg>
                    ) : (
                        <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 15v7"/><path d="M9 19h6"/><circle cx="12" cy="9" r="6"/></svg>
                    )}
                    <span className="font-bold text-base">{option.label}</span>
                    </button>
                ))}
            </div>
        </div>

        {/* Reference Image Section */}
        <div className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
             <label className="block text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Ảnh tham khảo (Tùy chọn)</label>
             <div 
                onClick={() => fileInputRef.current?.click()}
                className="border-2 border-dashed border-gray-600 rounded-xl p-6 flex flex-col items-center justify-center cursor-pointer hover:border-pink-500 hover:bg-gray-800 transition-all min-h-[150px]"
            >
                {referencePreview ? (
                    <div className="relative w-full h-48">
                        <img src={referencePreview} alt="Reference" className="w-full h-full object-contain rounded-lg" />
                        <button 
                            onClick={(e) => { e.stopPropagation(); setReferencePreview(null); setReferenceImageFile(null); updateField('referenceImage', undefined); }}
                            className="absolute top-2 right-2 bg-red-500 text-white p-1 rounded-full hover:bg-red-600"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" /></svg>
                        </button>
                    </div>
                ) : (
                    <>
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-gray-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                        <p className="text-gray-400 text-sm">Click để tải ảnh lên</p>
                    </>
                )}
                <input type="file" ref={fileInputRef} onChange={(e) => handleFileChange(e, false)} accept="image/*" className="hidden" />
            </div>
            
            {referencePreview && (
                 <button
                    onClick={(e) => { e.stopPropagation(); handleAIAnalyze('reference'); }}
                    disabled={isAnalyzing}
                    className="mt-4 w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3 rounded-lg transition-all shadow-lg flex items-center justify-center disabled:opacity-70"
                >
                    {isAnalyzing ? <LoadingSpinner /> : (
                        <>
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" /></svg>
                            Phân Tích & Hoàn Thiện từ Ảnh Này
                        </>
                    )}
                </button>
             )}
        </div>

        {/* CLONE CHARACTER SECTION - NEW FEATURE */}
        <div className="bg-gradient-to-br from-gray-900 to-gray-800 p-6 rounded-xl border border-pink-500/30 shadow-lg relative overflow-hidden group">
            <div className="absolute top-0 left-0 w-1 h-full bg-pink-500"></div>
            <div className="flex items-center gap-2 mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-pink-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
                <h3 className="text-lg font-bold text-white">Clone Nhân Vật Gốc <span className="text-pink-400 text-sm font-normal">(AI Vision)</span></h3>
            </div>
            <p className="text-gray-400 text-sm mb-4">Tải lên ảnh nhân vật gốc. AI sẽ phân tích "Visual DNA" (khuôn mặt, vóc dáng) để tạo bản sao kỹ thuật số hoàn hảo.</p>
            
            <div 
                onClick={() => cloneInputRef.current?.click()}
                className={`border-2 border-dashed ${clonePreview ? 'border-pink-500 bg-gray-800' : 'border-gray-600 hover:border-pink-400 hover:bg-gray-800'} rounded-xl p-4 flex flex-col items-center justify-center cursor-pointer transition-all min-h-[120px]`}
            >
                 {clonePreview ? (
                    <div className="flex items-center gap-4 w-full">
                        <img src={clonePreview} alt="Clone Source" className="w-20 h-20 object-cover rounded-lg border border-pink-500" />
                        <div className="flex-1">
                             <p className="text-white font-semibold text-sm">Đã tải ảnh gốc</p>
                             <p className="text-xs text-green-400">Sẵn sàng phân tích</p>
                        </div>
                        <button 
                            onClick={(e) => { e.stopPropagation(); setClonePreview(null); setCloneImageFile(null); }}
                            className="p-2 hover:bg-gray-700 rounded-full text-gray-400 hover:text-white"
                        >
                            Thay đổi
                        </button>
                    </div>
                ) : (
                    <div className="flex flex-col items-center text-center">
                        <div className="w-10 h-10 rounded-full bg-gray-700 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                             <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-pink-400" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" /></svg>
                        </div>
                        <span className="text-white font-bold text-sm">Tải ảnh lên để Clone</span>
                        <span className="text-xs text-gray-500 mt-1">Kéo thả hoặc nhấn để chọn ảnh</span>
                    </div>
                )}
                 <input type="file" ref={cloneInputRef} onChange={(e) => handleFileChange(e, true)} accept="image/*" className="hidden" />
            </div>

            {clonePreview && (
                <button
                    onClick={() => handleAIAnalyze('clone')}
                    disabled={isAnalyzing}
                    className="mt-4 w-full bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-500 hover:to-purple-500 text-white font-bold py-3 rounded-lg transition-all shadow-lg flex items-center justify-center disabled:opacity-70 disabled:cursor-not-allowed"
                >
                    {isAnalyzing ? <LoadingSpinner /> : (
                        <>
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" /></svg>
                            ✨ AI Phân Tích & Hoàn Thiện Tất Cả
                        </>
                    )}
                </button>
            )}
        </div>
    </div>
  );

  const renderStep2 = () => (
    <div className="space-y-6 animate-fade-in">
      <div>
        <label className="block text-sm font-bold text-gray-400 mb-2">Sắc tộc</label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {ETHNICITY_OPTIONS.map(opt => (
            <button key={opt.value} onClick={() => updateField('ethnicity', opt.value)} className={`p-3 rounded-lg border ${character.ethnicity === opt.value ? 'border-pink-500 bg-pink-900/30 text-white' : 'border-gray-700 bg-gray-800 text-gray-400'}`}>{opt.label}</button>
          ))}
        </div>
      </div>
      <div>
        <label className="block text-sm font-bold text-gray-400 mb-2">Tuổi: <span className="text-white">{character.age}</span></label>
        <input type="range" min="18" max="80" value={character.age} onChange={(e) => updateField('age', parseInt(e.target.value))} className="w-full accent-pink-500 h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer" />
      </div>
      <div>
         <label className="block text-sm font-bold text-gray-400 mb-2">Màu da</label>
         <div className="flex gap-2 overflow-x-auto pb-2">
           {SKIN_TONES.map(color => (
             <button key={color} onClick={() => updateField('skinTone', color)} style={{ backgroundColor: color }} className={`w-10 h-10 rounded-full border-2 flex-shrink-0 ${character.skinTone === color ? 'border-white scale-110' : 'border-transparent'}`} />
           ))}
         </div>
      </div>
      <div>
         <label className="block text-sm font-bold text-gray-400 mb-2">Màu mắt</label>
         <div className="flex gap-2 overflow-x-auto pb-2">
           {EYE_COLORS.map(color => (
             <button key={color} onClick={() => updateField('eyeColor', color)} style={{ backgroundColor: color }} className={`w-10 h-10 rounded-full border-2 flex-shrink-0 ${character.eyeColor === color ? 'border-white scale-110' : 'border-transparent'}`} />
           ))}
         </div>
      </div>
    </div>
  );

  const renderStep3 = () => (
     <div className="space-y-6 animate-fade-in">
        <div>
          <label className="block text-sm font-bold text-gray-400 mb-4">Kiểu tóc</label>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 max-h-[50vh] overflow-y-auto pr-2">
            {HAIR_STYLE_OPTIONS.map(opt => (
              <div key={opt.value} onClick={() => updateField('hairStyle', opt.value)} className={`cursor-pointer p-3 rounded-lg border transition-all ${character.hairStyle === opt.value ? 'border-pink-500 bg-pink-900/30' : 'border-gray-700 bg-gray-800 hover:bg-gray-700'}`}>
                 <div className="w-full h-24 bg-gray-900 rounded-md mb-2 overflow-hidden relative">
                    {opt.imageUrl ? <img src={opt.imageUrl} alt={opt.label} className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-gray-600"><opt.iconComponent className="w-8 h-8"/></div>}
                 </div>
                 <p className={`text-center text-sm font-semibold ${character.hairStyle === opt.value ? 'text-white' : 'text-gray-400'}`}>{opt.label}</p>
              </div>
            ))}
          </div>
        </div>
        <div>
            <label className="block text-sm font-bold text-gray-400 mb-2">Màu tóc</label>
            <div className="flex gap-2 overflow-x-auto pb-2">
                {HAIR_COLORS.map(color => (
                    <button key={color} onClick={() => updateField('hairColor', color)} style={{ backgroundColor: color }} className={`w-10 h-10 rounded-full border-2 flex-shrink-0 ${character.hairColor === color ? 'border-white scale-110' : 'border-transparent'}`} />
                ))}
            </div>
        </div>
     </div>
  );

  const renderStep4 = () => (
     <div className="space-y-6 animate-fade-in">
        <div className="bg-gray-800/50 p-4 rounded-lg">
            <label className="block text-sm font-bold text-gray-400 mb-3">Dáng người</label>
            <div className="flex justify-between gap-2 overflow-x-auto">
                 {BODY_TYPE_OPTIONS.map(opt => (
                     <button key={opt.value} onClick={() => updateField('bodyType', opt.value)} className={`flex-1 min-w-[80px] p-3 rounded-lg flex flex-col items-center gap-2 border ${character.bodyType === opt.value ? 'border-pink-500 bg-pink-900/20 text-white' : 'border-gray-700 bg-gray-900 text-gray-500'}`}>
                         {opt.iconComponent && <opt.iconComponent className="w-8 h-8"/>}
                         <span className="text-xs font-semibold">{opt.label}</span>
                     </button>
                 ))}
            </div>
        </div>
        
        {character.gender === Gender.Female && (
            <>
                <div className="bg-gray-800/50 p-4 rounded-lg">
                    <label className="block text-sm font-bold text-gray-400 mb-3">Vòng một</label>
                    <div className="flex justify-between gap-2 overflow-x-auto">
                         {BREAST_SIZE_OPTIONS.map(opt => (
                             <button key={opt.value} onClick={() => updateField('breastSize', opt.value)} className={`flex-1 min-w-[60px] p-2 rounded-lg flex flex-col items-center gap-1 border ${character.breastSize === opt.value ? 'border-pink-500 bg-pink-900/20 text-white' : 'border-gray-700 bg-gray-900 text-gray-500'}`}>
                                 {opt.iconComponent && <opt.iconComponent className="w-6 h-6"/>}
                                 <span className="text-xs">{opt.label}</span>
                             </button>
                         ))}
                    </div>
                </div>
                <div className="bg-gray-800/50 p-4 rounded-lg">
                    <label className="block text-sm font-bold text-gray-400 mb-3">Vòng ba</label>
                    <div className="flex justify-between gap-2 overflow-x-auto">
                         {BUTT_SIZE_OPTIONS.map(opt => (
                             <button key={opt.value} onClick={() => updateField('buttSize', opt.value)} className={`flex-1 min-w-[60px] p-2 rounded-lg flex flex-col items-center gap-1 border ${character.buttSize === opt.value ? 'border-pink-500 bg-pink-900/20 text-white' : 'border-gray-700 bg-gray-900 text-gray-500'}`}>
                                 {opt.iconComponent && <opt.iconComponent className="w-6 h-6"/>}
                                 <span className="text-xs">{opt.label}</span>
                             </button>
                         ))}
                    </div>
                </div>
            </>
        )}
     </div>
  );

  const renderStep5 = () => (
     <div className="space-y-6 animate-fade-in">
        <div className="flex justify-end">
            <button onClick={handleAutoGenerateDetails} disabled={isGeneratingDetails} className="text-xs flex items-center gap-1 text-pink-400 hover:text-pink-300 border border-pink-500/50 px-3 py-1.5 rounded-full hover:bg-pink-500/10 transition-colors">
                {isGeneratingDetails ? <LoadingSpinner /> : (
                    <>
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                        AI Tự Nghĩ
                    </>
                )}
            </button>
        </div>
        <div>
            <label className="block text-sm font-bold text-gray-400 mb-2">Tên nhân vật</label>
            <input type="text" value={character.name} onChange={(e) => updateField('name', e.target.value)} className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:border-pink-500 focus:outline-none" placeholder="Đặt tên cho nàng thơ..." />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label className="block text-sm font-bold text-gray-400 mb-2">Tính cách</label>
                <select value={character.personality} onChange={(e) => updateField('personality', e.target.value)} className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white">
                    {PERSONALITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                </select>
            </div>
            <div>
                <label className="block text-sm font-bold text-gray-400 mb-2">Nghề nghiệp</label>
                <select value={character.occupation} onChange={(e) => updateField('occupation', e.target.value)} className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white">
                    {OCCUPATION_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                </select>
            </div>
             <div>
                <label className="block text-sm font-bold text-gray-400 mb-2">Mối quan hệ</label>
                <select value={character.relationship} onChange={(e) => updateField('relationship', e.target.value)} className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white">
                    {RELATIONSHIP_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                </select>
            </div>
             <div>
                <label className="block text-sm font-bold text-gray-400 mb-2">Sở thích</label>
                <select value={character.hobby} onChange={(e) => updateField('hobby', e.target.value)} className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white">
                    {HOBBY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                </select>
            </div>
        </div>
     </div>
  );

  const renderStep6 = () => (
      <div className="space-y-6 text-center animate-fade-in">
          <div className="w-32 h-32 mx-auto rounded-full bg-gradient-to-r from-pink-500 to-purple-600 p-1">
              <div className="w-full h-full rounded-full bg-gray-900 flex items-center justify-center overflow-hidden">
                  {character.referenceImage || clonePreview ? (
                      <img src={character.referenceImage || clonePreview!} alt="Preview" className="w-full h-full object-cover" />
                  ) : (
                      <span className="text-4xl">✨</span>
                  )}
              </div>
          </div>
          <h2 className="text-2xl font-bold text-white">Sẵn sàng tạo {character.name || 'nhân vật'}?</h2>
          <div className="bg-gray-800/50 p-6 rounded-xl text-left space-y-2 max-w-md mx-auto text-sm text-gray-300">
              <p><strong className="text-gray-400">Giới tính:</strong> {character.gender}</p>
              <p><strong className="text-gray-400">Tuổi:</strong> {character.age}</p>
              <p><strong className="text-gray-400">Phong cách:</strong> {character.ethnicity}, {character.hairStyle}</p>
              <p><strong className="text-gray-400">Body:</strong> {character.bodyType}</p>
              <p><strong className="text-gray-400">Tính cách:</strong> {character.personality}</p>
          </div>
          <p className="text-gray-400 text-sm">AI sẽ tạo ra những hình ảnh đầu tiên và viết nên câu chuyện độc nhất cho nhân vật này.</p>
      </div>
  );

  return (
    <div className="max-w-4xl mx-auto">
      <ProgressBar currentStep={currentStep} onStepClick={setCurrentStep} />
      
      <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-6 md:p-10 shadow-2xl shadow-pink-500/5 backdrop-blur-sm min-h-[500px] flex flex-col">
        <div className="flex-grow">
            {currentStep === 1 && renderStep1()}
            {currentStep === 2 && renderStep2()}
            {currentStep === 3 && renderStep3()}
            {currentStep === 4 && renderStep4()}
            {currentStep === 5 && renderStep5()}
            {currentStep === 6 && renderStep6()}
        </div>

        <div className="mt-10 pt-6 border-t border-gray-800 flex justify-between items-center">
          {currentStep > 1 ? (
             <button onClick={() => setCurrentStep(prev => prev - 1)} className="text-gray-400 hover:text-white font-semibold px-4 py-2 rounded-lg hover:bg-gray-800 transition-colors">
               &larr; Quay lại
             </button>
          ) : (
             <button onClick={onBackToMenu} className="text-gray-400 hover:text-white font-semibold px-4 py-2 rounded-lg hover:bg-gray-800 transition-colors">
               Hủy bỏ
             </button>
          )}
          
          {currentStep < 6 ? (
            <button onClick={() => setCurrentStep(prev => prev + 1)} className="bg-white text-black font-bold py-3 px-8 rounded-full hover:bg-gray-200 transition-transform hover:scale-105 shadow-lg">
              Tiếp tục
            </button>
          ) : (
            <button onClick={() => onSave(character)} className="bg-gradient-to-r from-pink-500 to-purple-600 text-white font-bold py-3 px-10 rounded-full transition-transform hover:scale-110 shadow-xl shadow-pink-500/30 animate-pulse">
              Hoàn Tất & Tạo ✨
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default CharacterForm;